### ISSUE TITLE
Resume_header_intro not shown in print preview

### ISSUE THREAD

**Issue by abiduzz420** [jglovier/resume-template#47] opened 2017-11-14 18:55 UTC
The intro section at the beginning of the resume is not shown in print preview. I tried to save in PDF format and the Intro was omitted. The resume starts off directly with the Experience after my name.

**Comment by jglovier** [comment] 2017-11-15 23:47
@abiduzz420 thanks for the heads up. I'll look into it.

**Comment by Minimalistic** [comment] 2018-02-12 20:24
@abiduzz420 I could be mistaken, and @jglovier would certainly be the all-knower of all this, but I think that's default by design - or at least you could modify your specific resume's html to show it during a print event.  The class `no-print` is assigned to all elements that are to be omitted during a print - when you say "Intro" I am suspecting you're referring to the Executive Summary, if you have a look in the `~/_layouts/resume.html` file, and find the executive summary:

```html

<div class="executive-summary no-print" itemprop="description">
    {{ site.resume_header_intro }}
</div>
```

So if you have anything within your resume you would like to omit during a print or for that matter, display during a print, you can just append or remove the `no-print` class as necessary.

**Comment by abiduzz420** [comment] 2018-02-13 04:52
Thanks @Minimalistic That was helpful. `no-print` it is.

**Comment by jglovier** [comment] 2018-02-13 18:21
Yeah, that was added in #22, but I'm certainly open to PRs to modify the current behavior. 👍

**Closed as completed** 2018-05-15 18:13 UTC
